export enum RiskLevel {
  SAFE = 'SAFE',
  UNUSUAL = 'UNUSUAL',
  SUSPICIOUS = 'SUSPICIOUS',
}

export enum AppCategory {
  SOCIAL = 'SOCIAL',
  MESSAGING = 'MESSAGING',
  PHOTO = 'PHOTO',
  BROWSER = 'BROWSER',
  FINANCE = 'FINANCE',
  UTILITY = 'UTILITY',
  SYSTEM = 'SYSTEM',
  UNKNOWN = 'UNKNOWN',
}

export enum TrustLevel {
  TRUSTED = 'TRUSTED',
  NEUTRAL = 'NEUTRAL',
  UNKNOWN = 'UNKNOWN',
}

export enum SecurityEventType {
  PERMISSION_USED = 'PERMISSION_USED',
  FILE_ACCESS = 'FILE_ACCESS',
  BACKGROUND_ACTIVITY = 'BACKGROUND_ACTIVITY',
  PHOTO_ACCESS = 'PHOTO_ACCESS',
  CONTACT_ACCESS = 'CONTACT_ACCESS',
}

export enum RuleId {
  KNOWN_TRACKER = 'KNOWN_TRACKER',
  NEW_DOMAIN = 'NEW_DOMAIN',
  LARGE_UPLOAD = 'LARGE_UPLOAD',
  UNUSUAL_NETWORK_ACTIVITY = 'UNUSUAL_NETWORK_ACTIVITY',
  SENSITIVE_APP_BEHAVIOR = 'SENSITIVE_APP_BEHAVIOR',
}

export enum SimulatorScenario {
  NORMAL = 'NORMAL',
  UNUSUAL = 'UNUSUAL',
  HIGH_RISK = 'HIGH_RISK',
}

export enum VpnStatus {
  STOPPED = 'STOPPED',
  STARTING = 'STARTING',
  ACTIVE = 'ACTIVE',
  ERROR = 'ERROR',
  UNSUPPORTED = 'UNSUPPORTED',
}

export enum AlertAction {
  NONE = 'NONE',
  BLOCK = 'BLOCK',
  ALLOW = 'ALLOW',
  IGNORE = 'IGNORE',
}

export enum NetworkDirection {
  INBOUND = 'INBOUND',
  OUTBOUND = 'OUTBOUND',
}

export enum NetworkProtocol {
  TCP = 'TCP',
  UDP = 'UDP',
  OTHER = 'OTHER',
}
