export enum RiskLevel {
  SAFE = 'SAFE',
  UNUSUAL = 'UNUSUAL',
  SUSPICIOUS = 'SUSPICIOUS',
}

export enum AppCategory {
  SOCIAL = 'SOCIAL',
  PHOTO = 'PHOTO',
  UTILITY = 'UTILITY',
  SYSTEM = 'SYSTEM',
  UNKNOWN = 'UNKNOWN',
}

export enum TrustLevel {
  TRUSTED = 'TRUSTED',
  NEUTRAL = 'NEUTRAL',
  UNKNOWN = 'UNKNOWN',
}

export enum SecurityEventType {
  PERMISSION_USED = 'PERMISSION_USED',
  FILE_ACCESS = 'FILE_ACCESS',
  BACKGROUND_ACTIVITY = 'BACKGROUND_ACTIVITY',
  PHOTO_ACCESS = 'PHOTO_ACCESS',
  CONTACT_ACCESS = 'CONTACT_ACCESS',
}

export enum RuleId {
  KNOWN_TRACKER = 'KNOWN_TRACKER',
  NEW_DOMAIN = 'NEW_DOMAIN',
  LARGE_UPLOAD = 'LARGE_UPLOAD',
  UNUSUAL_NETWORK_ACTIVITY = 'UNUSUAL_NETWORK_ACTIVITY',
  SENSITIVE_APP_BEHAVIOR = 'SENSITIVE_APP_BEHAVIOR',
}

export enum SimulatorScenario {
  NORMAL = 'NORMAL',
  UNUSUAL = 'UNUSUAL',
  HIGH_RISK = 'HIGH_RISK',
}
